import { useState } from "react";
import { CSVLink } from "react-csv";

import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Button from "@mui/joy/Button";
import FormControl from "@mui/material/FormControl";
import InputLabel from "@mui/material/InputLabel";
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";

import Navbar from "./components/Navbar";
import InputForm from "./components/InputForm";

import { listKategory } from "./Kategori";

import "./styles.css";

export default function App() {
  const [judul, setJudul] = useState("");
  const [deskripsi, setDeskripsi] = useState("");
  const [harga, setHarga] = useState(0);
  const [label, setLabel] = useState("");
  const [kategori, setKategori] = useState("");
  const [gambar1, setGambar1] = useState("");
  const [gambar2, setGambar2] = useState("");
  const [gambar3, setGambar3] = useState("");
  const [gambar4, setGambar4] = useState("");
  const [gambar5, setGambar5] = useState("");
  const [gambar6, setGambar6] = useState("");
  const [gambar7, setGambar7] = useState("");
  const [gambar8, setGambar8] = useState("");
  const [gambar9, setGambar9] = useState("");
  const [gambar10, setGambar10] = useState("");

  return (
    <div className="App">
      <Navbar />

      <Box sx={{ my: 5, maxWidth: "500px", mx: "auto" }}>
        {/* Judul field */}
        <InputForm
          title="Judul"
          state={judul}
          setState={setJudul}
          inputType="text"
        />
        {/* Deskripsi field */}
        <TextField
          label="Deskripsi"
          variant="outlined"
          fullWidth={true}
          defaultValue={deskripsi}
          rows={5}
          sx={{ mb: 3 }}
          multiline
          onChange={(e) => setDeskripsi(e.target.value)}
        />
        {/* Harga field */}
        <InputForm
          title="Harga"
          state={harga}
          setState={setHarga}
          inputType="number"
        />
        {/* Kategori field */}
        <FormControl size="small" sx={{ mb: 2 }} fullWidth>
          <InputLabel id="Kategori">Kategori</InputLabel>
          <Select
            labelId="Kategori"
            label="Kategori"
            onChange={(e) => setKategori(e.target.value)}
          >
            <MenuItem value="semua">Pilih semua</MenuItem>
            {listKategory.map((item, key) => (
              <MenuItem value={item} key={key}>
                {item}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
        {/* Label field */}
        <InputForm
          title="Label"
          state={label}
          setState={setLabel}
          inputType="text"
        />
        {/* Gambar1 - Gambar10 field */}
        <InputForm
          title="gambar1"
          state={gambar1}
          setState={setGambar1}
          inputType="text"
        />
        <InputForm
          title="gambar2"
          state={gambar2}
          setState={setGambar2}
          inputType="text"
        />
        <InputForm
          title="gambar3"
          state={gambar3}
          setState={setGambar3}
          inputType="text"
        />
        <InputForm
          title="gambar4"
          state={gambar4}
          setState={setGambar4}
          inputType="text"
        />
        <InputForm
          title="gambar5"
          state={gambar5}
          setState={setGambar5}
          inputType="text"
        />
        <InputForm
          title="gambar6"
          state={gambar6}
          setState={setGambar6}
          inputType="text"
        />
        <InputForm
          title="gambar7"
          state={gambar7}
          setState={setGambar7}
          inputType="text"
        />
        <InputForm
          title="gambar8"
          state={gambar8}
          setState={setGambar8}
          inputType="text"
        />
        <InputForm
          title="gambar9"
          state={gambar9}
          setState={setGambar9}
          inputType="text"
        />
        <InputForm
          title="gambar10"
          state={gambar10}
          setState={setGambar10}
          inputType="text"
        />

        {/* end of gambar field */}

        <Button>
          <CSVLink
            headers={headers}
            className="save"
            data={[
              {
                Judul: "PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Peralatan",
                Lokasi:
                  "Kota Administrasi Jakarta Selatan, Daerah Khusus Ibukota Jakarta",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mebel",
                Lokasi:
                  "Kota Administrasi Jakarta Pusat, Daerah Khusus Ibukota Jakarta",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Peralatan Rumah Tangga",
                Lokasi:
                  "Kota Administrasi Jakarta Barat, Daerah Khusus Ibukota Jakarta",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BERGARANSI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Kebun",
                Lokasi:
                  "jakarta timur, Kota Administrasi Jakarta Timur, Daerah Khusus Ibukota Jakarta 13650",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Perkakas",
                Lokasi: "Magelang",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Video Game",
                Lokasi: "Pati, Jawa Tengah, Indonesia",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERBARU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Buku, Film, & Musik",
                Lokasi: "Pekalongan",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Tas & Koper",
                Lokasi: "Pemalang",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Wanita",
                Lokasi: "Purbalingga, Jawa Tengah, Indonesia",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Pria",
                Lokasi: "Rembang, Jawa Tengah, Indonesia",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG SALE! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Perhiasan & Aksesori",
                Lokasi: "Kota Salatiga",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BISA COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Kesehatan & Kecantikan",
                Lokasi: "Semarang, Indonesia",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua"
                    ? kategori
                    : "Kebutuhan Hewan Peliharaan",
                Lokasi: "Sragen, Jawa Tengah, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERPERCAYA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Bayi & Anak-Anak",
                Lokasi: "Sukoharjo",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PRODUK ASLI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mainan & Game",
                Lokasi: "Surakarta",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "CUCI GUDANG! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Elektronik & Komputer",
                Lokasi: "Tegal, Jawa Tengah",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Telepon Seluler",
                Lokasi: "Temanggung, Jawa Tengah, Indonesia",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Sepeda",
                Lokasi: "Wonogiri, Jawa Tengah, Indonesia",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO GILA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Seni & Kerajinan",
                Lokasi: "Wonosobo, Jawa Tengah, Indonesia",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA GROSIR! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Olahraga & Outdoor",
                Lokasi: "Bandung",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Komponen Otomotif",
                Lokasi: "Kota Banjar",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW ARRIVAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Alat Musik",
                Lokasi: "Bekasi",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Barang Antik & Koleksi",
                Lokasi: "Bogor, Indonesia",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Cuci Gudang",
                Lokasi: "Ciamis, Jawa Barat, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERKEREN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Lain-lain",
                Lokasi: "Kabupaten Cianjur",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLAKU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Peralatan",
                Lokasi: "Kota Cimahi",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mebel",
                Lokasi: "Cirebon",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERJAMIN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Peralatan Rumah Tangga",
                Lokasi: "Depok",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Kebun",
                Lokasi: "Garut",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "LARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Perkakas",
                Lokasi: "Indramayu",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TOP SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Video Game",
                Lokasi: "Karawang",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Buku, Film, & Musik",
                Lokasi: "Kuningan, Indonesia",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PALING LARIS " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Tas & Koper",
                Lokasi: "Majalengka",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Wanita",
                Lokasi: "Bangkalan, Bangkalan",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Pria",
                Lokasi: "Banyuwangi, Jawa Timur",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Perhiasan & Aksesori",
                Lokasi: "Kota Batu",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BERGARANSI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Kesehatan & Kecantikan",
                Lokasi: "Blitar",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua"
                    ? kategori
                    : "Kebutuhan Hewan Peliharaan",
                Lokasi: "Bojonegoro",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Bayi & Anak-Anak",
                Lokasi: "Kabupaten Bondowoso",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERBARU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mainan & Game",
                Lokasi: "Gresik",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Elektronik & Komputer",
                Lokasi: "Jember",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Telepon Seluler",
                Lokasi: "Jombang, Jawa Timur, Indonesia",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Sepeda",
                Lokasi: "Kediri",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG SALE! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Seni & Kerajinan",
                Lokasi: "Lamongan",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BISA COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Olahraga & Outdoor",
                Lokasi: "Lumajang",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Komponen Otomotif",
                Lokasi: "Madiun",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERPERCAYA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Alat Musik",
                Lokasi: "Magetan, Jawa Tengah, Indonesia",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PRODUK ASLI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Barang Antik & Koleksi",
                Lokasi: "Malang",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "CUCI GUDANG! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Cuci Gudang",
                Lokasi: "Mojokerto",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Lain-lain",
                Lokasi: "Nganjuk",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Peralatan",
                Lokasi: "Ngawi, Jawa Tengah, Indonesia",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO GILA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mebel",
                Lokasi: "Kabupaten Pamekasan",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA GROSIR! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Peralatan Rumah Tangga",
                Lokasi: "Pasuruan",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Kebun",
                Lokasi: "Ponorogo",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW ARRIVAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Perkakas",
                Lokasi: "Probolinggo",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Video Game",
                Lokasi: "Sampang, Jawa Timur, Indonesia",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Buku, Film, & Musik",
                Lokasi: "Sidoarjo, Jawa Timur, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERKEREN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Tas & Koper",
                Lokasi: "Kabupaten Situbondo",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLAKU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Wanita",
                Lokasi: "Kabupaten Sumenep",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Pria",
                Lokasi: "Surabaya, Indonesia",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERJAMIN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Perhiasan & Aksesori",
                Lokasi: "Kabupaten Trenggalek",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Kesehatan & Kecantikan",
                Lokasi: "Tuban, Jawa Timur, Indonesia",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "LARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua"
                    ? kategori
                    : "Kebutuhan Hewan Peliharaan",
                Lokasi: "Tulungagung",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TOP SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Bayi & Anak-Anak",
                Lokasi: "Banjarnegara, Jawa Tengah, Indonesia",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mainan & Game",
                Lokasi: "Banyumas, Jawa Tengah",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PALING LARIS " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Elektronik & Komputer",
                Lokasi: "Batang, Jawa Tengah, Indonesia",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Telepon Seluler",
                Lokasi: "Blora, Jawa Tengah, Indonesia",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Sepeda",
                Lokasi: "Boyolali, Jawa Tengah, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Seni & Kerajinan",
                Lokasi: "Brebes, Jawa Tengah, Indonesia",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BERGARANSI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Olahraga & Outdoor",
                Lokasi: "Cilacap",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Komponen Otomotif",
                Lokasi: "Demak, Demak",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Alat Musik",
                Lokasi: "Grobogan, Jawa Tengah, Indonesia",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERBARU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Barang Antik & Koleksi",
                Lokasi: "Jepara",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Cuci Gudang",
                Lokasi: "Karanganyar",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Lain-lain",
                Lokasi: "Kebumen, Jawa Tengah, Indonesia",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Peralatan",
                Lokasi: "Klaten, Jawa Tengah, Indonesia",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BIG SALE! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mebel",
                Lokasi: "Kudus",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BISA COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Peralatan Rumah Tangga",
                Lokasi: "Purwakarta",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Kebun",
                Lokasi: "Subang, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERPERCAYA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Perkakas",
                Lokasi: "Sukabumi",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PRODUK ASLI! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Video Game",
                Lokasi: "Sumedang",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "CUCI GUDANG! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Buku, Film, & Musik",
                Lokasi: "Tasikmalaya",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "COD! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Tas & Koper",
                Lokasi: "Bantul, Bantul",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Wanita",
                Lokasi: "Sleman, Sleman",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO GILA! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Pakaian & Sepatu Pria",
                Lokasi: "Yogyakarta",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA GROSIR! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Perhiasan & Aksesori",
                Lokasi: "Gamping, Yogyakarta, Indonesia",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "HARGA TERMURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Kesehatan & Kecantikan",
                Lokasi: "Mlati, Special Region of Yogyakarta",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "NEW ARRIVAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua"
                    ? kategori
                    : "Kebutuhan Hewan Peliharaan",
                Lokasi: "Mergangsan, Special Region of Yogyakarta",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "DISKON MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Bayi & Anak-Anak",
                Lokasi: "Denpasar, Bali, Indonesia",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MENARIK! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Mainan & Game",
                Lokasi: "Badung, Bali, Indonesia",
                Delay: 40000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERKEREN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Elektronik & Komputer",
                Lokasi: "Kabupaten Tabanan",
                Delay: 29000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERLAKU! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Telepon Seluler",
                Lokasi: "Klungkung, Bali, Indonesia",
                Delay: 33000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "MURAH! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Sepeda",
                Lokasi: "Buleleng, Bali, Indonesia",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TERJAMIN! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Seni & Kerajinan",
                Lokasi: "Jembrana, Bali, Indonesia",
                Delay: 45000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "ORIGINAL! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Olahraga & Outdoor",
                Lokasi: "Batam, Riau, Indonesia",
                Delay: 32000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "LARIS! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Komponen Otomotif",
                Lokasi: "Jakarta, Indonesia",
                Delay: 38000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "TOP SELLER! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Alat Musik",
                Lokasi: "Makassar",
                Delay: 30000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "BEST PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori:
                  kategori !== "semua" ? kategori : "Barang Antik & Koleksi",
                Lokasi: "Banten, Jawa Barat, Indonesia",
                Delay: 34000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PALING LARIS " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Cuci Gudang",
                Lokasi: "Tangerang",
                Delay: 55000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
              {
                Judul: "PROMO! " + judul,
                Deskripsi: `${deskripsi}`,
                Harga: `${harga}`,
                Kategori: kategori !== "semua" ? kategori : "Lain-lain",
                Lokasi: "Serang",
                Delay: 35000,
                Label: `${label}`,
                Gambar1: `${gambar1}`,
                Gambar2: `${gambar2}`,
                Gambar3: `${gambar3}`,
                Gambar4: `${gambar4}`,
                Gambar5: `${gambar5}`,
                Gambar6: `${gambar6}`,
                Gambar7: `${gambar7}`,
                Gambar8: `${gambar8}`,
                Gambar9: `${gambar9}`,
                Gambar10: `${gambar10}`,
              },
            ]}
          >
            Download
          </CSVLink>
        </Button>
      </Box>
    </div>
  );
}

const headers = [
  { label: "Judul", key: "Judul" },
  { label: "Deskripsi", key: "Deskripsi" },
  { label: "Harga", key: "Harga" },
  { label: "Kategori", key: "Kategori" },
  { label: "Lokasi", key: "Lokasi" },
  { label: "Delay", key: "Delay" },
  { label: "Label", key: "Label" },
  { label: "Gambar1", key: "Gambar1" },
  { label: "Gambar2", key: "Gambar2" },
  { label: "Gambar3", key: "Gambar3" },
  { label: "Gambar4", key: "Gambar4" },
  { label: "Gambar5", key: "Gambar5" },
  { label: "Gambar6", key: "Gambar6" },
  { label: "Gambar7", key: "Gambar7" },
  { label: "Gambar8", key: "Gambar8" },
  { label: "Gambar9", key: "Gambar9" },
  { label: "Gambar10", key: "Gambar10" },
];
