const listKategory = [
  "Peralatan",
  "Mebel",
  "Peralatan Rumah Tangga",
  "Kebun",
  "Perkakas",
  "Video Game",
  "Buku, Film, & Musik",
  "Tas & Koper",
  "Pakaian & Sepatu Wanita",
  "Pakaian & Sepatu Pria",
  "Perhiasan & Aksesori",
  "Kesehatan & Kecantikan",
  "Kebutuhan Hewan Peliharaan",
  "Bayi & Anak-Anak",
  "Mainan & Game",
  "Elektronik & Komputer",
  "Telepon Seluler",
  "Sepeda",
  "Seni & Kerajinan",
  "Olahraga & Outdoor",
  "Komponen Otomotif",
  "Alat Musik",
  "Barang Antik & Koleksi",
  "Cuci Gudang",
  "Lain-lain",
];

export { listKategory };
